powerpc/tm: Limit TM code inside PPC_TRANSACTIONAL_MEM
Commit e1c3743e1a20 ("powerpc/tm: Set MSR[TS] just prior to recheckpoint")
moved a code block around and this block is now using a variable 'msr'
outside of the CONFIG_PPC_TRANSACTIONAL_MEM, however the 'msr' variable is
just declared inside the CONFIG_PPC_TRANSACTIONAL_MEM block, causing a
possible error:

	error: 'msr' undeclared (first use in this function)

This is not causing a compilation error in the upstream kernel, because
'msr' is being used by MSR_TM_ACTIVE(), which is defined as the following
when CONFIG_PPC_TRANSACTIONAL_MEM is *not* set:

	#define MSR_TM_ACTIVE(x) 0

This patch just fixes this issue limiting the 'msr' usage from inside a
CONFIG_PPC_TRANSACTIONAL_MEM block.

Cc: stable@vger.kernel.org
Fixes: e1c3743e1a20 ("powerpc/tm: Set MSR[TS] just prior to recheckpoint")
Signed-off-by: Breno Leitao <leitao@debian.org>